# Generated by Django 5.0.7 on 2025-11-22 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('strategy', 'Стратегические'), ('family', 'Семейные'), ('party', 'Для вечеринок'), ('cooperative', 'Кооперативные'), ('card', 'Карточные'), ('rpg', 'Ролевые')], max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена покупки')),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена аренды за день')),
                ('min_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальное количество игроков')),
                ('max_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество игроков')),
                ('play_time_minutes', models.PositiveIntegerField(verbose_name='Время игры (минуты)')),
                ('difficulty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность (1-5)')),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='В наличии для покупки')),
                ('available_for_rental', models.PositiveIntegerField(default=0, verbose_name='Доступно для аренды')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название столика')),
                ('table_type', models.CharField(choices=[('small', 'Маленький (2-4 человека)'), ('medium', 'Средний (4-6 человек)'), ('large', 'Большой (6-8 человек)'), ('vip', 'VIP (8+ человек)')], max_length=10, verbose_name='Тип столика')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('price_per_hour_per_person', models.DecimalField(decimal_places=2, default=60.0, max_digits=6, verbose_name='Цена за час за человека')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Игровой столик',
                'verbose_name_plural': 'Игровые столики',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='GameRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('rental_end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.customer', verbose_name='Клиент')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Аренда игры',
                'verbose_name_plural': 'Аренды игр',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('shipping_address', models.TextField(verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.customer', verbose_name='Клиент')),
                ('games', models.ManyToManyField(through='tablegames.OrderItem', to='tablegames.game', verbose_name='Игры')),
            ],
            options={
                'verbose_name': 'Заказ на покупку',
                'verbose_name_plural': 'Заказы на покупку',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.purchaseorder', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('number_of_people', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.customer', verbose_name='Клиент')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablegames.gametable', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Бронирование столика',
                'verbose_name_plural': 'Бронирования столиков',
                'unique_together': {('table', 'booking_date', 'start_time')},
            },
        ),
    ]
